### ISSUE TITLE
昆工大的大佬

### ISSUE THREAD

**Issue by kangkang623** [chiupam/surge#1]
你好ꉂ೭(˵¯̴͒ꇴ¯̴͒˵)౨”

**Comment by chiupam** [comment]
其实我是隔壁昆医的 你是想用js吗？

**Comment by kangkang623** [comment]
> 其实我是隔壁昆医的 你是想用js吗？

我在找有什么薅羊毛的新脚本，看见新的就看了下，看见你脚本里面签到的大学…我再去找找有啥一键签到的新脚本

**Comment by chiupam** [comment]
狗东 快手 酷狗 饿了么 最近都挺热门 更新一点的我就没关注了
