### ISSUE TITLE
掌上飞车圈x获取cookie语法错误

### ISSUE THREAD

**Issue by Trasshhhh** [chiupam/surge#2]
如题 无法应用语法

**Comment by chiupam** [comment]
App签到改版了 一直拖着没更新 等收假我再开始写吧

**Comment by Trasshhhh** [comment]
收到 祝你生活愉快~

**Comment by chiupam** [comment]
搞了几天 应该可以用了 后续有bug会继续修复 你试试这个文件 [zsfc.v3.js](https://github.com/chiupam/surge/blob/main/scripts/javascripts/zsfc.v3.js) 配置文件怎么写和脚本怎么获取cookie都在开头注释部分了

**Comment by chiupam** [comment]
你测试途中有什么bug欢迎提出 如果没什么问题了这个issues会被关闭

**Comment by Trasshhhh** [comment]
> 搞了几天 应该可以用了 后续有bug会继续修复 你试试这个文件 [zsfc.v3.js](https://github.com/chiupam/surge/blob/main/scripts/javascripts/zsfc.v3.js) 配置文件怎么写和脚本怎么获取cookie都在开头注释部分了

很可惜 他依然在圈叉显示语法错误，line270，zsfc.js/zsfc-V3.js，

**Comment by Trasshhhh** [comment]
问题出现在rewrite_local中的引用
“^https://mwegame\.qq\.com/ams/sign/doSign/month url scripts-request-body https://raw.githubusercontent.com/chiupam/surge/main/scripts/javascripts/zsfc.js” 
这里，引用语法错误。

**Comment by chiupam** [comment]
先确认脚本名称吧 我这边仓库是改成了[zsfc.v3.js](https://github.com/chiupam/surge/blob/main/scripts/javascripts/zsfc.v3.js) 在chavyleung仓库依旧还是[zsfc.js](https://github.com/chavyleung/scripts/blob/master/zsfc/zsfc.js) 可以点击对应链接去查看头部的配置

**Comment by chiupam** [comment]
你QX对应的配置应该是
```properties
[MITM]
hostname = comm.ams.game.qq.com

[rewrite_local]
^https://mwegame\.qq\.com/ams/sign/doSign/month url scripts-request-body https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js

[task_local]
0 10 0,21 * * * https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js, tag=掌上飞车, enabled=true
```
配置对比上一个版本来说 基本都是重写了的

**Comment by chiupam** [comment]
噢噢 发现了 原来是正则表达式没有改过来 那我再去修改一下

**Comment by chiupam** [comment]
正确的配置应该是下列才对
```properties
[MITM]
hostname = comm.ams.game.qq.com

[rewrite_local]
^https?://comm\.ams\.game\.qq\.com/ams/ame/amesvr* url scripts-request-body https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js

[task_local]
0 10 0,21 * * * https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js, tag=掌上飞车, enabled=true
```
这样配置起来应该就对了

**Comment by Trasshhhh** [comment]
> 正确的配置应该是下列才对
> 
> ```properties
> 
> [MITM]
> 
> hostname = comm.ams.game.qq.com
> 
> 
> 
> [rewrite_local]
> 
> ^https?://comm\.ams\.game\.qq\.com/ams/ame/amesvr* url scripts-request-body https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js
> 
> 
> 
> [task_local]
> 
> 0 10 0,21 * * * https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js, tag=掌上飞车, enabled=true
> 
> ```
> 
> 这样配置起来应该就对了


 [rewrite_local]依旧是显示语法错误啊啊啊
我可以给你提供我买的
quantumultx 的id，你或许需要？

**Comment by Trasshhhh** [comment]
我不知道一个正确的rewrite_local该怎么写，但我配置里有几个正确的script-request-body供您参考 ，语法获取cookie的地址：

#微信小程序伊犁乳品
https:\/\/club\.yili\.com\/MALLIFChe\/MCSWSIAPI\.asmx\/Call -url script-request-body https://raw.githubusercontent.com/id77/QuantumultX/master/task/yiLi.cookie.js

#威锋
^https?:\/\/api.wfdata.club\/v1\/auth\/signin -url script-request-body https://raw.githubusercontent.com/chavyleung/scripts/master/feng/feng.cookie.js

#NGA社区
^https:\/\/ngabbs.com\/nuke.php\?? -url script-request-body https://raw.githubusercontent.com/chouchoui/QuanX/master/Scripts/nga/nga.cookie.js

**Comment by chiupam** [comment]
倒也不用 我有 就是不咋用qx 我去下一个来试试

**Comment by chiupam** [comment]
好了 我现在qx版本是1.4.1−813，使用我仓库地址的话配置如下
```properties
[rewrite_local]
^https?://comm\.ams\.game\.qq\.com/ams/ame/amesvr* url script-request-body https://raw.githubusercontent.com/chiupam/surge/main/scripts/javascripts/zsfc.v3.js

[task_local]
0 10 0,21 * * * https://raw.githubusercontent.com/chiupam/surge/main/scripts/javascripts/zsfc.v3.js, tag=掌上飞车, enabled=true

[mitm]
hostname = comm.ams.game.qq.com
```

下面用的chavyleung仓库地址，你可以上下两个任选一个
```properties
[rewrite_local]
^https?://comm\.ams\.game\.qq\.com/ams/ame/amesvr* url script-request-body https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js

[task_local]
0 10 0,21 * * * https://raw.githubusercontent.com/chavyleung/scripts/master/zsfc/zsfc.js, tag=掌上飞车, enabled=true

[mitm]
hostname = comm.ams.game.qq.com
```
